# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60c8d2943c9c6972f6e2d2c5ea1911827f075086684e370ffb28bb01afd28a25977eb19f83042c6e00c26247f6dc53162420330feda758fa690dd21b7719e96d

test:
  secret_key_base: 19cca134d06a180cc8ef1f8ef5512b0fdb8b96a4d02c79147465e993ef232364e44da9651a24df112a8030612b8b6199a4494eb129d64176c9251dfa6c76bf96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
